; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qualia_s3_rgb666]
platform = espressif32 @ 6.11.0 ;anything higher than 6.11.0 causes build errors
board = adafruit_qualia_s3_rgb666
framework = arduino
lib_deps = 
	lvgl/lvgl @ 9.2.2 ;anything higher than 9.2.2  or 9.3.0 causes build errors
	moononournation/GFX Library for Arduino @ 1.6.0 ;anything higher than 1.6.0 causes build errors
	LittleFS @ ^2.0.0
	h2zero/NimBLE-Arduino @ ^2.3.4
	bblanchon/ArduinoJson @ ^7.4.2
build_flags = 
	-Iinclude